version: 1.0.{build}
image: visual studio 2022
build_script:

- cmd: echo "AppVeyor"

test: off

#---------------------------------#

#  Skip builds for doc changes    #

#---------------------------------#

skip_commits:

  # Regex for matching commit message

  message: /\(doc\).*/

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
